FROM ubuntu:16.04

RUN DEBIAN_FRONTEND=noninteractive \
&& apt-get update -y \
&& DEBIAN_FRONTEND=noninteractive apt-get install -y apt-utils curl wget nginx && mkdir /files

ADD nginx.conf /etc/nginx/nginx.conf
ADD onko-spb /usr/share/nginx/html

EXPOSE 80

CMD ["nginx","-g","daemon off;"]
